language: python

matrix:
  include:
  - python: '2.7'
    env:
    - PYTHON_VERSION="2.7"
    - PYTEST_ARGS="--cov=rca"
    - COVERALLS="true"
  - python: '3.5'
    env:
    - PYTHON_VERSION="3.5"
    - PYTEST_ARGS="--cov=rca"
    - COVERALLS="true"
  - python: '3.6'
    env:
    - PYTHON_VERSION="3.6"
    - PYTEST_ARGS="--cov=rca"
    - COVERALLS="true"
  - python: '3.6'
    env:
    - PYTHON_VERSION="3.6"
    - PYTEST_ARGS="--cov=rca"
    - COVERALLS="true"
    - DOC_BUILD="true"
  - python: '3.7-dev'
    env:
    - PYTHON_VERSION="3.7"
    - PYTEST_ARGS="--cov=rca"
    - COVERALLS="true"
    allow_failures:
      python: "3.7-dev"
