#!/usr/bin/env python
import numpy as np
import os
import glob
import json
import csv


def create_hourly_csv(radar_config_file, date):
    """
    create_hourly_csv creates a CSV file specifically for keeping track of
    hourly RCA values generated by hourly_rca.py 
    
    Parameters
    ----------
    radar_config_file: str
        path to JSON file containing specifications: data directory, file
extension, clutter map directory, output directory for baseline netCDF,
baseline date, scan type, polarization, site, instrument, range limit
    date: str
        YYYYMMDD                
    """

    config_vars = json.load(open(radar_config_file))
    daily_csv_dir = config_vars["daily_csv_dir"]
    scantype = config_vars["scan_type"]
    polarization = config_vars["polarization"]
    site = config_vars["site_abbrev"]
    inst = config_vars["instrument_abbrev"]

    header = ["DATE", "RCA_H", "RCA_V", "NUM_PTS", "NUM_PTS_V", "PASS_FILTER", "RH"]
    daily_csv = daily_csv_dir + "/hourlies/" + "hourly_rca_" + scantype + "_" + site + inst + "_" + date + ".csv"
    with open(daily_csv, "w", newline="") as f:
        writer = csv.writer(f, delimiter=",")
        writer.writerow(header)  # write the header
